---
- name: setup node
  hosts: all
  vars_files:
    - vars.yml
  gather_facts: true
  sudo: true

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=604800 # 1 week in seconds (7*24*3600)

    - name: install dependencies
      apt: 
        package: "{{ system_packages }}"

    - name: install python packages
      pip:
        name: "{{ item }}"
      with_items: "{{ python_packages }}"

    - name: uninstall nginx
      apt:
        package: nginx
        state: absent

    - name: create user groups
      group: name={{item.name}} state={{item.state | default('present')}} 
      with_items: "{{ users }}"

    - name: Add users
      user: 
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}" 
        password: "{{ item.password }}"
        group: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "/bin/bash"
      with_items: "{{ users }}"

    - name: disable root login
      lineinfile: "dest=/etc/ssh/sshd_config state=present regexp='^PermitRootLogin' line='PermitRootLogin no'"

    - name: enable password authentication
      lineinfile: "dest=/etc/ssh/sshd_config state=present regexp='^PasswordAuthentication' line='PasswordAuthentication yes'"

    - name: enable password less sudo for users in sudo group
      lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL:ALL) NOPASSWD:ALL'"

    - name: start ml-lab container
      docker_container:
        name: ml-lab
        image: pipalacademy/ml-lab
        env:
          JUPYTERLAB_TOKEN: "{{ JUPYTERLAB_TOKEN }}"
        volumes:
          - /home/ml/notebooks:/tf/notebooks
        ports:
          - "0.0.0.0:80:8888"
        restart_policy: always
